### ISSUE TITLE
Update to node 16+

### ISSUE THREAD

**Issue by nickpell** [turtlequeue/setup-babashka#16]
I've been seeing this warning in GitHub Actions annotations:

```Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: turtlequeue/setup-babashka@v1.5.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.```

**Comment by nha** [comment]
Thanks!

**Comment by srenatus** [comment]
I believe we still need a new release/tag for this message to go away? I'm seeing it, too 🤭
